Homework
Olgadani/recipesnew pull request #1
Opened 2023-01-01 20:09 UTC by Olgadani

2023-01-14 17:42 UTC, OlgaLugacheva requested changes

2023-01-14 17:42 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipesnew/services/IngredientServiceimpl.java
> +
`@Service`

2023-01-14 17:42 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipesnew/services/RecipeServiceimpl.java
> +
`@Service`

2023-01-18 20:40 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipesnew/services/RecipeServiceimpl.java
> +    public RecipeServiceimpl(@Value("application.file.recipes") String path) {
Тут нужно делать вот так, `@Value("${application.file.recipes}"`, чтобы бралось именно значение.

2023-01-23 15:40 UTC, iStemmer commented on src/main/java/pro/sky/recipesnew/controllers/IngredientController.java
> +    public ResponseEntity<byte[]> downloadIngredients() throws IOException {
IOException надо ловить через try-catch и выкидывать свое исключение

2023-01-23 15:40 UTC, iStemmer commented on src/main/java/pro/sky/recipesnew/controllers/IngredientController.java
> +    public void importIngredients(MultipartFile ingredients) throws IOException {
IOException надо ловить через try-catch и выкидывать свое исключение

2023-01-23 15:49 UTC, iStemmer commented on src/main/java/pro/sky/recipesnew/services/RecipeServiceimpl.java
> +            e.printStackTrace();
тут надо выкидывать свое исключение, чтобы дать понять о том, что что-то пошло не так

2023-01-23 15:49 UTC, iStemmer commented on src/main/java/pro/sky/recipesnew/services/RecipeServiceimpl.java
> +            e.printStackTrace();
тут надо выкидывать свое исключение, чтобы дать понять о том, что что-то пошло не так

2023-01-23 15:49 UTC, iStemmer commented on src/main/java/pro/sky/recipesnew/services/RecipeServiceimpl.java
> +            e.printStackTrace();
тут надо выкидывать свое исключение, чтобы дать понять о том, что что-то пошло не так

2023-01-23 18:49 UTC, Olgadani commented on src/main/java/pro/sky/recipesnew/controllers/IngredientController.java
> +    public ResponseEntity<byte[]> downloadIngredients() throws IOException {
не поняла, как это сделать. после удаления куска "throws IOException" идея не дает вставить try-catch - отмечает красным и предлагает удалить.

2023-01-25 18:56 UTC, merged